name: Clang Format AutoFix

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format-autofix:
    name: Auto-fix Formatting
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push to PR branches

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install clang-format 15
      run: sudo apt-get update && sudo apt-get install -y clang-format-15

    - name: Run clang-format
      run: |
        find SRC -regex '.*\.\(c\|cpp\|h\|hpp\)' -exec clang-format-15 -i {} +

    - name: Commit and push formatting fixes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        if ! git diff --quiet; then
          git add SRC
          git commit -m "chore: autoformat code using clang-format"
          git push
        else
          echo "No formatting changes necessary."
        fi
