name: Clang format check and autofix

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  formatting-check:
    name: Formatting Check & Autofix
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get install -y clang-format-14

    - name: Run clang-format and detect changes
      run: |
        find SRC -regex '.*\.\(c\|cpp\|h\|hpp\)' -exec clang-format-14 -i {} +
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        if ! git diff --quiet; then
          git add .
          git commit -m "chore: autoformat with clang-format"
          git push
        else
          echo "No formatting changes needed."
        fi
